---
title: "Power for mediation"
author: Marcello Gallucci 
topic: mediation
category: help
bibliography: 
     - bib.bib
link-citations: true
        
---


```{r echo=FALSE,results='hide'}
library(mcdocs)
mcdocs_init()


```

`r version("0.4.0")`

`r pic("pics/mediation/ui.png")`

`Mediation power analysis` allows for computing power parameters for testing indirect (mediated) effects in several mediational models. It can be used to estimate power parameters based on the `Sobel test`, `joint significance` or `Monte Carlo` method. 

`r incomplete`


The initial step is to determine the objective of the analysis ( _aim_ ). Further details regarding different objectives can be found in the `Info` results field.

`r pic("pics/common/aim.1.png")`


The second step is to decide what type of model we are dealing with. 

# Models

* __Simple mediation (three variables)__ : This is the classical simple mediation, with one independent variable, one mediator. The model looks like this
`r pic("pics/mediation/diagram.1.png")`

* __Complex mediation models__ : Allows computation of power parameters for more complex models: two parallel mediator, three parallel mediator and serial mediation with two mediators. They are, respectively:

`r pic("pics/mediation/diagram.2.png")`



# Simple Mediation Model

In simple mediation models there is one independent variable, one mediator and one dependent variable. The model is:

`r pic("pics/mediation/diagram.1.png")`

The `a` coefficient is the simple standardized coefficient of a regression from X to M (mediator). `b` and `c'` are the standardized coefficients of a multiple regression with $Y$ as dependent variable and $X$ and $M$ as independent variables.



`r include_pages(topic="mediation",category="rosetta",title="Validation")`

`r issues()`

`r backto()`


`r backto()`

`r issues()`
